language: php

sudo: false

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=5.0.*
    - php: 7.2
      env: SYMFONY_VERSION=5.1.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=5.1.*


cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/flex --no-update; composer config extra.symfony.require "${SYMFONY_VERSION}"; fi;
  - composer update --prefer-source

script: vendor/bin/phpunit --coverage-clover=coverage.clover